NUCLEI_SDK_ROOT ?= ../../../nuclei-sdk

SRCDIRS = .
# ../../.. is <tinymaix> folder
INCDIRS = . include ../..

COMMON_FLAGS ?= -O3

STDCLIB ?= newlib_small

# when ARCH_EXT=pv P-ext and V-ext will be enabled
# and P-ext/V-ext optimized library will be selected
# see NMSIS/build.mk
SOC ?= demosoc
CORE ?= n300fd
DOWNLOAD ?= ilm
ARCH_EXT ?=
LDLIBS ?= -lm
# see tinymaix.h
# proper values startswith TM_MDL_*, such as TM_MDL_INT8
# eg. TM_MDL_TYPE=TM_MDL_FP32
TM_MDL_TYPE ?=

ifneq ($(TM_MDL_TYPE),)
COMMON_FLAGS += -DTM_MDL_TYPE=$(TM_MDL_TYPE)
endif

# use different linker script file for evalsoc and demosoc
# when DOWNLOAD=ilm, this will work with the best_config bitstream
# download from nuclei internal http://doc/cpu_signoff/
ifeq ($(DOWNLOAD),ilm)
ifeq ($(SOC),demosoc)
LINKER_SCRIPT ?= ../gcc_512K.ld
endif
ifeq ($(SOC),evalsoc)
LINKER_SCRIPT ?= ../gcc_512K.ld
endif
endif

MIDDLEWARE_TINYMAIX := ../..

include $(MIDDLEWARE_TINYMAIX)/build.mk

include $(NUCLEI_SDK_ROOT)/Build/Makefile.base
